"use strict";
exports.__esModule = true;
var profile_1 = require("./model/profile");
var circle = require("./model/circle");
var export_default_1 = require("./model/export-default");
var _ = require("lodash");
profile_1.v1();
profile_1.v2();
console.log("面积：" + circle.area(2));
console.log("周长：" + circle.circumference(3));
export_default_1["default"]();
console.log(_.add(1, 2));
